if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
  message(FATAL_ERROR "LambdaEmbedBinary requires INPUT, OUTPUT, and SYMBOL")
endif()

file(READ "${INPUT}" _lambda_bytes HEX)
string(LENGTH "${_lambda_bytes}" _lambda_hex_len)
math(EXPR _lambda_byte_len "${_lambda_hex_len} / 2")

set(_lambda_out "static constexpr unsigned char ${SYMBOL}[] = {")
set(_lambda_col 0)
foreach(_lambda_i RANGE 0 ${_lambda_hex_len} 2)
  if(_lambda_i EQUAL _lambda_hex_len)
    break()
  endif()
  string(SUBSTRING "${_lambda_bytes}" ${_lambda_i} 2 _lambda_byte)
  if(_lambda_col EQUAL 0)
    string(APPEND _lambda_out "\n  ")
  endif()
  string(APPEND _lambda_out "0x${_lambda_byte},")
  math(EXPR _lambda_col "${_lambda_col} + 1")
  if(_lambda_col EQUAL 12)
    set(_lambda_col 0)
  else()
    string(APPEND _lambda_out " ")
  endif()
endforeach()
string(REGEX REPLACE " $" "" _lambda_out "${_lambda_out}")
string(APPEND _lambda_out "\n};\nstatic constexpr unsigned int ${SYMBOL}_len = ${_lambda_byte_len};\n")
file(WRITE "${OUTPUT}" "${_lambda_out}")
